p1/newyear/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index)
]

p1/p1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('newyear/', include('newyear.urls')),
    path('tasks/', include('tasks.urls')),
]

p1/tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'
urlpatterns = [
    path('', views.home, name="index"),
    path('add/', views.add, name="add")
]

p1/newyear/models.py
from django.db import models

# Create your models here.

p1/tasks/models.py
from django.db import models

# Create your models here.

p1/newyear/views.py
from django.shortcuts import render
from django.http import request

import datetime

now = datetime.datetime.now()
month = now.month
day = now.day

if month == 1 and day == 1 :
    isNewYear = 'Yes'
else :
    isNewYear = 'No'


# Create your views here.


def index(request):
    return render(request, 'index.html', {
        "newYear" : isNewYear
    })

p1/tasks/views.py
from django import forms
from django.shortcuts import render

tasks = ['foo', 'bar', 'baz']

class NewTaskForm(forms.Form):
    task_name = forms.CharField(label='task name')

def home(request):
    return render(request, 'tasks/index.html', {
        'tasks' : tasks
    })


def add(request):
    return render(request, 'tasks/add/add.html', {
        'form' : NewTaskForm()
    })

p1/newyear/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Year</title>
    <link rel="shortcut icon" href="./icon.png" type="image/png">

    <style>
        body {
            height: 100vh;
            width: 100%;

            display: flex;
            align-items: center;
            justify-content: center;
            overflow: hidden;
            background: coral;
        }
        h1 {
            font-family: sans-serif;
            font-size: 100px;
            color: #ddd;
        }
    </style>
</head>
<body>
    <h1>{{newYear}}</h1>
</body>
</html>

p1/tasks/templates/tasks/add/add.html
{% extends 'tasks/base.html' %}

{% block body %}

<h1>Add Task</h1>

    <!-- <form action="{% url 'tasks:add' %}" method="POST">
        {% csrf_token %}
        <label for="task_name">task name: </label>
        <input type="text" name="task" id="task_name">
        
        <input type="submit" value="submit">
    </form> -->

        {{ form }}
    <a href="{% url 'tasks:index' %}">Back to tasks</a>

{% endblock %}

p1/tasks/templates/tasks/add/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks | Add</title>
</head>
<body>
    
</body>
</html>

p1/tasks/templates/tasks/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

p1/tasks/templates/tasks/index.html
{% extends 'tasks/base.html' %}

{% block body %}
<h1>Tasks</h1>
<ol>
  {% for task in tasks %}
  <li>{{ task }}</li>
  {% endfor %}
</ol>
<a href="{% url 'tasks:add' %}">Add task</a>

{% endblock %}